# Generated by Django 4.2.2 on 2023-10-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyattendance",
            name="company",
        ),
    ]
