# Generated by Django 4.2.2 on 2023-10-05 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_remove_dailyattendance_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyattendance",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
