# Generated by Django 4.2.2 on 2023-10-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="ipv6",
            field=models.CharField(default="1", max_length=100),
        ),
    ]
