# Generated by Django 4.2.2 on 2023-10-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_employee_ipv6"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="ipv6",
        ),
    ]
