# Generated by Django 4.2.2 on 2023-10-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_remove_employee_ipv6"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="ipv4",
            field=models.CharField(default="0", max_length=100),
        ),
    ]
